### ISSUE TITLE
[DOC]: Write individual contribution

### ISSUE THREAD

**Issue by cmougan** [cmougan/WRI_WellBeing_Data_Layer#13]
@rohaan2614 @sunayana @GvdDool  In the part of Project Organization, could you add how have you contributed to the project?

Also, if you want to do some self marketing and describe your bio or current position you can do it here :) :)

**Comment by rohaan2614** [comment]
Just confirming, 
I don't see any additions in the readme so I guess we are not doing this, right?

**Comment by cmougan** [comment]
@rohaan2614  I closed it since there was no feedback. But if you want you can.

**Comment by rohaan2614** [comment]
Okay.

I am gonna follow the team. Whatever you guys are doing, I will do too.
