### ISSUE TITLE
[DOC]: Table of contents, Development

### ISSUE THREAD

**Issue by cmougan** [cmougan/WRI_WellBeing_Data_Layer#20]
In the table of contents, there are some items:
- getting started
- main components
- contribution guidelines)

Are they there because we are going to document them in the future or we should erase them?

**Comment by sunayana** [comment]
@cmougan : When I see the README.md these sections were added when you aligned the project to follow [policy-data-organizer](https://github.com/wri-dssg/policy-data-analyzer#contribution-guidelines) project of wri-dssg. I think it is a good idea, so I will add some of these sections on Tuesday (27.04). Before that I am a bit busy.

**Comment by sunayana** [comment]
Closing this issue since this has been completed.
