### ISSUE TITLE
[DOC] : Notes on Data Preparation

### ISSUE THREAD

**Issue by sunayana** [cmougan/WRI_WellBeing_Data_Layer#9]
- [x] Add a sub section on Data Preparation at the beginning of the section on Project Methodology.
- [x] Introduce the data preparation pipeline with Voronoi 
- [x] Introduce improvement with weighted Voronoi and future work with weighted Voronoi + OSM and weighted Voronoi + NTL data

**Comment by sunayana** [comment]
@GvdDool : Sorry about the delay, so now I have completed all the sections and will wait for your comments.
@cmougan : I will again go through the readme later tonight and look if something is missing. So hopefully we should be ready to submit tomorrow.

**Comment by cmougan** [comment]
I will do the same now.
